os:
- linux
language: python
python:
- '3.4'
- '3.5'
install:
- pip install tox-travis
- python setup.py install
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: danwos
  password:
    secure: KjXVTOVfklhGehD82I1PLInp3bK7KjBe0Mj24FeEwjcW7vUN13Pwb0BVuTdiqpep3K5mq8yNCjwWeXD45yz/1uiuOgLXx76oIhTlgkkgtRe3wSPbFDgv0q3P5+atP6ID4s1m1FXbKtSN+wZcXWtJPhweqDi665HNMYii0claYlQeamTqMbYV23BNx/b3U6YU6R1Eaa28UnpYdPslroibEFp8Bv/T/SBLxYlY4ws/C+suyhHVbplgG3aieZz9nkbO+9O2MqQwtLEqpmjh2R8IutvuD9eTskGo3X4ajCn/ECZt5Wp5KoZ7sI14Qxur2O0km+jEQNcB+/BEeg+zeeI2eOX/q58SwCmKEufdrykwM02V9+TcFJWxtetIy+ISES6yb5LrT84hPmMuAkP7QGEvrvERuS716yEQDs/GECZPt+4WZruTjsVkN6FiNc4b6Z04buePsIUu1neMCLJdR9qfhFY2zHJfh0LZyI8/nGiwm/p9NEjl3Pc755t+DMc6423hjJl8ta8z13ZJcpgGjZG6ZQeB71b0cJjSlf0ym8qttg2wERXs77BAQtoA3x5Gj9x6amiki0RuXTbb9UNaYHB3XwoMbM+uqhMpVw4S31mC+iWYkPO4XhZFoSq8GIv+6UJfNeHkRNi/t6WnHZ4CPiUnVLDDG13BwOGmxPha/YCAwjY=
  on:
    tags: true
    branch: master
